apiVersion: harness.io/v1
kind: Component
type: service
identifier: java_rothschild_ten
name: Java Rothschild Ten
owner: user:account/dustin.rothschild@harness.io
orgIdentifier: default
projectIdentifier: default_project
spec:
  lifecycle: development
  sourceCode:
    provider: Github
    repoName: kai-java-rothschild-ten
    connectorRef: account.ghharnessidpsandbox
    branch: main
    monoRepo: false
    url: https://github.com/harness-idp-sandbox/kai-java-rothschild-ten/tree/main
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: kai-java-rothschild-ten
    grafana/dashboard-selector: folderUrl == 'https://100.25.3.28.sslip.io/dashboards/f/bf34szb60u2gwe/harness'
    grafana/overview-dashboard: https://100.25.3.28.sslip.io/d/19a44328-b2d2-4fb2-bfa3-d379d069124a/jvm-micrometer?orgId=1&kiosk&var-application=java-rothschild-ten
    sonarqube.org/project-key: parson/java-rothschild-ten
    backstage.io/kubernetes-label-selector: app=javarothschildten
    harness.io/pipelines: |
      Build and Deploy: https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/all/orgs/sandbox/projects/parson/pipelines/Java_App_Provisioner/pipeline-studio/?storeType=INLINE
  links:
  - title: Website
    url: http://harness.io
  tags:
  - java
